export let options = [
  { label: "Wi-Fi", value: "wifi" },
  { label: "Televisión por cable", value: "tv" },
  { label: "Aire Acondicionado", value: "aac" },
  { label: "Agua potable", value: "water" },
  { label: "Luz", value: "light" },
  { label: "Gas", value: "gas" },
  { label: "Calefacción", value: "heating" },
  { label: "Cocina", value: "kitchen" },
  { label: "Estacionamiento", value: "parking" },
  { label: "Piscina", value: "pool" },
  { label: "Gimnasio", value: "gym" },
  { label: "Mascotas", value: "pets" },
  { label: "Amueblado", value: "furnished" },
  { label: "Lavadora", value: "washer" },
  { label: "Secadora", value: "dryer" },
  { label: "Ascensor", value: "elevator" },
  { label: "Fraccionamiento Privado", value: "private" },
  { label: "Portero", value: "doorman" },
  { label: "Areá de lavado", value: "laundry" },
  { label: "Patio", value: "yard" },
  { label: "Terraza", value: "terrace" },
  { label: "Balcón", value: "balcony" },
  { label: "Vigilancia", value: "surveillance" },
];
